#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

DTS_DEVICE="/dev/mmcblk0boot1"
DTS_OFFSET=160
DTS_SIZE=32
DTS_FILE="current_dts_type.txt"

echo "Reading current DTS type..."
dd if=$DTS_DEVICE of=$DTS_FILE bs=1 count=$DTS_SIZE skip=$DTS_OFFSET
CURRENT_DTS_TYPE=$(cat $DTS_FILE | tr -d '\0')
echo "Current DTS type: $CURRENT_DTS_TYPE"

DTS_TYPES=(
    "@BM1688_EVB:"
    "bm1688_wevb_4G"
    "bm1688_wevb_8G"
    "bm1688_wevb_12G"
    "bm1688_wevb_16G"
    "@CV186AH_EVB:"
    "cv186ah_wevb_4G"
    "cv186ah_wevb_8G"
    "cv186ah_wevb_12G"
    "cv186ah_wevb_16G"
    "@BM1688_NVR:"
    "bm1688_nvrv1_4G"
    "bm1688_nvrv1_8G"
    "bm1688_nvrv1_12G"
    "bm1688_nvrv1_16G"
    "@CV186AH_NVR:"
    "cv186ah_nvrv1_4G"
    "cv186ah_nvrv1_8G"
    "cv186ah_nvrv1_12G"
    "cv186ah_nvrv1_16G"
    "@SE9-16:"
    "bm1688_se9v1_4G"
    "bm1688_se9v1_8G"
    "bm1688_se9v1_12G"
    "bm1688_se9v1_16G"
    "@SE9-8:"
    "cv186ah_se9v1_4G"
    "cv186ah_se9v1_8G"
    "cv186ah_se9v1_12G"
    "cv186ah_se9v1_16G"
    "@SM9-16:"
    "bm1688_sm9v1_4G"
    "bm1688_sm9v1_8G"
    "bm1688_sm9v1_12G"
    "bm1688_sm9v1_16G"
    "@SM9-8:"
    "cv186ah_sm9v1_4G"
    "cv186ah_sm9v1_8G"
    "cv186ah_sm9v1_12G"
    "cv186ah_sm9v1_16G"
)


echo "Please select the DTS type by entering the corresponding number:"
index=1
for dts in "${DTS_TYPES[@]}"; do
    if [[ $dts == \@* ]]; then 
        echo "$dts"
    else
        echo "$index) $dts"
    fi
	let index+=1
done

read -p "Enter the number (1-$(($index-1))): " DTS_NUMBER

if ! [[ "$DTS_NUMBER" =~ ^[0-9]+$ ]] || [ "$DTS_NUMBER" -lt 1 ] || [ "$DTS_NUMBER" -ge "$index" ]; then
    echo "Invalid selection. Exiting."
    exit 1
fi

actual_index=0
selected_index=0
for dts in "${DTS_TYPES[@]}"; do
    if [[ $dts != \$* ]]; then
        let actual_index+=1
        if [ "$actual_index" -eq "$DTS_NUMBER" ]; then
            break
        fi
    fi
    let selected_index+=1
done

DTS_TYPE="${DTS_TYPES[$selected_index]}"
echo "You selected: $DTS_TYPE"

DTS_TYPE="${DTS_TYPES[$selected_index]}"
echo "You selected: $DTS_TYPE"

DTS_FILE="dts_type.txt"
DTS_DEVICE="/dev/mmcblk0boot1"
DTS_OFFSET=160
DTS_SIZE=32

echo 0 > /sys/block/mmcblk0boot1/force_ro
dd if=/dev/zero of=$DTS_DEVICE count=$DTS_SIZE bs=1 seek=$DTS_OFFSET

echo -n "$DTS_TYPE" > $DTS_FILE
dd if=$DTS_FILE of=$DTS_DEVICE count=$DTS_SIZE bs=1 seek=$DTS_OFFSET

dd if=$DTS_DEVICE of=$DTS_FILE bs=1 count=$DTS_SIZE skip=$DTS_OFFSET

READ_BACK_DTS_TYPE=$(cat $DTS_FILE)
if [ "$READ_BACK_DTS_TYPE" == "$DTS_TYPE" ]; then
    echo "DTS_TYPE is successfully written and verified: $READ_BACK_DTS_TYPE"
else
    echo "Error: DTS_TYPE verification failed"
    exit 1
fi

echo "DTS_TYPE setting and verification completed."

