#!/bin/bash

hostname=$(hostname)
uptimeInfo=$(uptime --pretty)

chip=`cat /sys/class/thermal/thermal_zone0/temp`
board=`cat /sys/class/thermal/thermal_zone0/temp`
chip_temp=`expr $chip / 1000`
board_temp=`expr $board / 1000`

chip_sn=$(cat /factory/OEMconfig.ini | grep "SN" | awk -F \= 'NR==1{print $2}')

product_sn=$(cat /factory/OEMconfig.ini | grep "DEVICE_SN" | awk -F \= '{print $2}')

product=$(cat /factory/OEMconfig.ini | grep "PRODUCT =" | awk -F \= '{print $2}')

chip=$(cat /factory/OEMconfig.ini | grep "CHIP =" | awk -F \= '{print $2}')


echo "------------------------------------------------------------------------"
echo "product: $product"
echo "chip: $chip"
echo "chip sn: $chip_sn"
echo "device sn:$product_sn"
echo "hostname: $hostname"
echo "uptimeInfo: $uptimeInfo"
echo "boardtemperature: $board_temp"
echo "coretemperature: $chip_temp"
echo "------------------------------------------------------------------------"

