#!/bin/bash

chip=$(cat /factory/OEMconfig.ini | grep "CHIP =" | awk -F= '{print $2}' | sed 's/^ *//')
echo "SophonSDK($chip) 2.0"

#soc mode
dpkg -l | grep sophon-soc-libsophon | awk '{printf "%s : %s\n",$2,$3}'
dpkg -l | grep sophon-media-soc-sophon-ffmpeg | awk '{printf "%s : %s\n",$2,$3}'
dpkg -l | grep sophon-media-soc-sophon-opencv | awk '{printf "%s : %s\n",$2,$3}'
#pcie mode
dpkg -l | grep sophon-libsophon | awk '{printf "%s : %s\n",$2,$3}'
dpkg -l | grep sophon-media-sophon-ffmpeg | awk '{printf "%s : %s\n",$2,$3}'
dpkg -l | grep sophon-media-sophon-opencv | awk '{printf "%s : %s\n",$2,$3}'

if [ -f "/opt/sophon/libsophon-current/bin/version" ] \
    && dpkg -l | grep -q "sophon-soc-libsophon"; then
    /opt/sophon/libsophon-current/bin/version
fi
kern_version=$(uname -a)
echo "KernelVersion : $kern_version"\

