#!/bin/sh

dpkg -l | grep sophon-soc-libsophon | awk '{printf "%s : %s\n",$2,$3}'
dpkg -l | grep sophon-mw-soc-sophon-ffmpeg | awk '{printf "%s : %s\n",$2,$3}'
dpkg -l | grep sophon-mw-soc-sophon-opencv | awk '{printf "%s : %s\n",$2,$3}'
version
kern_version=$(uname -a)
echo "KernelVersion : $kern_version"
hw_version=$(awk "/pcb version/" /sys/bus/i2c/devices/1-0017/information |awk -F \"  '{ print $4}')
echo "HWVersion: $hw_version"
mcu_version=$(awk "/mcu version/" /sys/bus/i2c/devices/1-0017/information |awk -F \"  '{ print $4}')
echo "MCUVersion: $mcu_version"
