network:
        version: 2
        renderer: networkd
        ethernets:
                eth0:
                        dhcp4: no
                        addresses: [192.168.150.1/24]
                        gateway4: 192.168.150.100
                        nameservers:
                                addresses: [8.8.8.8,114.114.114.114]
                        optional: yes
                eth1:
                        dhcp4: yes
                        addresses: []
                        optional: yes
                        dhcp-identifier: mac
