#
# Copyright (C) 2016 Samsung Electronics
# Thomas Abraham <thomas.ab@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_PINCTRL_BITMAIN)		+= pinctrl-bitmain.o
obj-$(CONFIG_PINCTRL_BM1684)	+= pinctrl-bm1684.o
obj-$(CONFIG_PINCTRL_MANGO)	+= pinctrl-mango.o
